spring:
  config:
    import: "optional:file:./secret.properties"

notion:
  api-url: https://api.notion.com
  api-version: 2022-02-22
  database-id: 828b4bab95f0409eb6326d31c3bb3682

server:
  port: 8082
