/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import org.springframework.cloud.openfeign.EnableFeignClients;
import project.config.NotionConfigProperties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties(value = {NotionConfigProperties.class})
@EnableFeignClients
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}
